import { createTransliterationTableWithLowerCase, type TransliterationSystem } from '../table';

// https://www.loc.gov/catdir/cpso/romanization/russian.pdf
export const alaLc: TransliterationSystem = {
  name: 'ALA-LC (Library of Congress) - Russian',
  table: createTransliterationTableWithLowerCase({
    А: 'A',
    Б: 'B',
    В: 'V',
    Г: 'G',
    Д: 'D',
    Е: 'E',
    Ё: 'Ë',
    Ж: 'Zh',
    З: 'Z',
    И: 'I',
    І: 'Ī',
    Й: 'Ĭ',
    К: 'K',
    Л: 'L',
    М: 'M',
    Н: 'N',
    О: 'O',
    П: 'P',
    Р: 'R',
    С: 'S',
    Т: 'T',
    У: 'U',
    Ф: 'F',
    Х: 'Kh',
    Ц: 'T\u0361S',
    Ч: 'Ch',
    Ш: 'Sh',
    Щ: 'Shch',
    Ъ: '\u02B9',
    Ы: 'Y',
    Ь: '\u02B9',
    Ѣ: 'I\u0361E',
    Э: 'Ė',
    Ю: 'I\u0361U',
    Я: 'I\u0361A',
    Ѳ: 'Ḟ',
    Ѵ: 'Ẏ',
  }),
};
